### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ozgurgundogan** [igniterealtime/REST-API-Client#10]
For some (developer maybe does not have Maven or . .), dependencies could be given in /lib directory as  .jar file since it is really time consuming to obtain dependencies to make client api work.

**Comment by guusdk** [comment]
I'm not in favor of adding binaries to the source project.

If your project does not use any dependency framework like Maven, you can still use Maven to collect all the dependencies that you need for your project:

    mvn dependency:copy-dependencies

This will create a directory in `target/dependency` that contains everything you need.

**Comment by Redor** [comment]
As guusdk said, I think as well that we shouldn't store the binaries
