### ISSUE TITLE
How to add contcat in Roster without sending and accepting subscription request 

### ISSUE THREAD

**Issue by rajscet** [igniterealtime/REST-API-Client#14]
Hello,
Thanks for great source code.
I have download and import the source code in eclipse

I want to implement adding contact in Roster without sending and receiving subscription request in our application,

is there any way to implement this task ??
please reply me if you know any solution.

To - Reader
Thanks for reading an Issue

**Comment by Redor** [comment]
I think you can create a shared group in Openfire (with everyone). So everyone will be in a roster of other and you don't need to implement something.

**Comment by rajscet** [comment]
i have solved it using Rest API. Now i able to create users and add contacts for individual user without send and accept request
