### ISSUE TITLE
Delete from chatroom missing

### ISSUE THREAD

**Issue by sputt** [igniterealtime/REST-API-Client#15]
I don't see any of the DELETE calls for /restapi/v1/chatrooms/ URLs

**Comment by Redor** [comment]
// Delete a chat room
  restApiClient.deleteChatRoom("chatroom1");

**Comment by sputt** [comment]
E.g. deleteMember, deleteAdmin, etc is what I meant

**Comment by Redor** [comment]
Yes, thats not there yet, and will be implemented soon, or you make a pull request :)
