### ISSUE TITLE
Signal errors with exceptions instead of returning `null`

### ISSUE THREAD

**Issue by netmikey** [igniterealtime/REST-API-Client#17]
In my client code, I want to be able to handle error situations like "channel not found", "bad credentials" etc.

In your current implementation, `org.igniterealtime.restclient.RestClient.call(...)`, you only log error messages in the `isStatusCodeOK(...)` call, but you ultimately return `null` on any error. This prevents client code from handling errors accordingly.

Please either let JAXRS' `ResponseProcessingException`, `ProcessingException` and `WebApplicationException` through, or introduce business exceptions for all possible error cases.

**Comment by Redor** [comment]
Fixed in 1.1.4
