### ISSUE TITLE
MUC: Add support for group affiliations

### ISSUE THREAD

**Issue by netmikey** [igniterealtime/REST-API-Client#18]
Openfire added the ability to assign entire user groups as MUC's owner, admin, member and outcast.

The REST API Plugin already exposes them as `ownerGroups`, `adminGroups`, `memberGroups` and `outcastGroups` (see https://www.igniterealtime.org/projects/openfire/plugins/restapi/readme.html#chatroom).

Please add those fields to the `MUCRoomEntity` so that client code can read and write them.

**Comment by Redor** [comment]
Fixed in 1.1.4
