### ISSUE TITLE
Update MUC room does not update subject of the group chat

### ISSUE THREAD

**Issue by malidipak1** [igniterealtime/REST-API-Client#19]
Started using openfire API in our application and using  REST-API client extensively. Have tried to update the group subject using MUC update API call but it does not take effect. 

If the same is updated from web console, it updates the subject of the MUC group immediately. 

Also, looked into the  code of API and web console, i found that the change of subject notification event have been taken care in JSP files of web console and the same not updated in REST API client code.

Thanks in advance for looking at this issue. Expect your comments and views for its solution. Let me know if it has already been addressed.

Thanks,
Dipak

**Comment by akrherz** [comment]
Thanks, have filed this as [OF-1274](https://issues.igniterealtime.org/browse/OF-1274)
