### ISSUE TITLE
duplicate entry

### ISSUE THREAD

**Issue by Shree9126** [igniterealtime/REST-API-Client#22]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: javax/inject/Inject.class

dependencies {
     androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.0'
    testCompile 'junit:junit:4.12'
      compile 'org.igniterealtime:rest-api-client:1.1.3'

}

**Comment by Redor** [comment]
Issue is not REST API CLIENT specific
