### ISSUE TITLE
igniterealtime/REST-API-Client » Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug' - Getting this error while running the application.

### ISSUE THREAD

**Issue by Shree9126** [igniterealtime/REST-API-Client#25]
I too face like that issue. If any one help me.. It'll be very helpful to me. I don't know what to do. I'm very suffer in these phase. I hope someone help me.

**Comment by Redor** [comment]
Could not be reproduced

**Comment by sviktor87** [comment]
same problem
