### ISSUE TITLE
Send message Api to a group and to specific user

### ISSUE THREAD

**Issue by goodlifechris** [igniterealtime/REST-API-Client#26]
Would like to get the api to send to a specific user

**Comment by Redor** [comment]
The REST API dont allow that (have not implemented it). So it can also not be implemented to the REST API Client

**Comment by deleolajide** [comment]
There is the ofchat plugin based on the Rest API plugin that does that. It is still work in progress

https://discourse.igniterealtime.org/t/rest-api-send-messages/79579
