### ISSUE TITLE
delete a user will not cleanup table USERSTATUS and USERSTATUSHISTORY

### ISSUE THREAD

**Issue by q16marvin** [igniterealtime/REST-API-Client#27]
Hi.

i use the rest api to cleanup my openfire (delete old users)... i workes well, but the old users are still in the table USERSTATUS and USERSTATUSHISTORY.

would be cool that this tables will also cleaned :)

Thx!

Erik

**Comment by guusdk** [comment]
Hey, thanks for this suggestion. Such an improvement should best be made in the userstatus plugin, not in the rest api client. I've created a new issue in our bugtracker for this: https://issues.igniterealtime.org/browse/OF-1537
