### ISSUE TITLE
Availability on mvnrepository / sonatype

### ISSUE THREAD

**Issue by jrouly** [igniterealtime/REST-API-Client#3]
I would love to use this library, but the Openfire REST API Client isn't available on mvnrepository or sonatype. Are there any plans to make this library available at any of the above (or similar) central repositories?

**Comment by Redor** [comment]
Hey,
Yes I will put it to central Maven repository in the near future.
Best

**Comment by Redor** [comment]
I already started with the process. But I have several issues which I need to find out how it works. (PGP signing etc.)

**Comment by jrouly** [comment]
Oh awesome, thanks for the follow up. I'll keep an eye out :smiley:

**Comment by Redor** [comment]
I added the project to maven central and adjusted the readme. 
```
<dependency>
    <groupId>org.igniterealtime</groupId>
    <artifactId>rest-api-client</artifactId>
    <version>1.0.0</version>
</dependency>
```
