### ISSUE TITLE
UserEntity‘s filed properties , how to work?

### ISSUE THREAD

**Issue by 1528992118** [igniterealtime/REST-API-Client#32]
As you can see , I used `restApiClient.getUsers()`, here's my return. Why these properties are all empty ?
I want to know these properties are extra  information from user table or other ? Sorry to bother you. I can't find introduce from `REST API Plugin Readme`
<pre>
{
	"users": [{
			"email": "051338",
			"name": "051338",
			"password": null,
			"properties": [],
			"username": "051338"
		},
		{
			"email": "050140",
			"name": "050140",
			"password": null,
			"properties": [],
			"username": "050140"
		}
	]
}
</pre>

**Comment by Redor** [comment]
Hey such I remember, properties is a separate table which is linked with user table.
Try to create a user with properties with the rest api client, and you should able to see entries there.

**Comment by 1528992118** [comment]
OK，thans for your answer.
