### ISSUE TITLE
Returning error 500

### ISSUE THREAD

**Issue by antoniomorais360** [igniterealtime/REST-API-Client#41]
I follow the instructions and authenticate normally, but all requests return error 500.
In log, sounds normally:
2019.12.14 17:29:07 org.jivesoftware.openfire.user.DefaultUserProvider - Results: 2
2019.12.14 17:29:07 org.jivesoftware.openfire.user.DefaultUserProvider - getUsers results: admin,antonio,.

Server: Openfire 4.4.4 running in Ubuntu 18.04 LTS
Client: Postman 7.13

![Capture](https://user-images.githubusercontent.com/2750015/70852446-d7484280-1e77-11ea-8992-d2f7a168cebb.PNG)

**Comment by Redor** [comment]
Which version of the Openfire and Rest API are you using?
And can you show me your headers? (you just need the authentication there)

**Comment by antoniomorais360** [comment]
First try:  Openfire 4.4.4 
Rest API 1.3.9 (provided in openfire plugin page) 
and Rest API 1.3.10-SNAPSHOT | Dec 13 
using **Postman**
https://ibb.co/dMgc1XK (error 500)

Second try:  Openfire 4.4.4, 
Rest API 1.3.9 (provided in openfire plugin page) 
and Rest API 1.3.10-SNAPSHOT | Dec 13 
using **Chrome** (just Authorization header)
https://ibb.co/1vpw1j9  (error ERR_INVALID_RESPONSE)

Third try:  Openfire 4.4.4, 
Rest API 1.3.9 (provided in openfire plugin page) 
and Rest API 1.3.10-SNAPSHOT | Dec 13 
using **Ubuntu CURL** (just Authorization header)
https://ibb.co/71YW473 (empty)

When I look at the log in openfire server, it shows the users
https://ibb.co/DfT5SGj

May I share here also? https://github.com/igniterealtime/openfire-restAPI-plugin
Tks for your help

**Comment by Redor** [comment]
I removed your comment, because it had authentication information (so that everyone could abuse it)
Do you see any error logs? (not the info.log)

**Comment by antoniomorais360** [comment]
No recent errors registered in error.log. 

Debug log:
<show>away</show>
<priority>1</priority>
<status>Working: 1 out of 2 executors are busy.</status>
<presence id="MTh66-4325" from="jenkins@foxmanager.com.br/6nm97jtbli">
2019.12.15 18:01:37 org.jivesoftware.openfire.plugin.ContentFilterPlugin - Content filter: intercepted packet:
2019.12.15 18:01:37 org.apache.mina.filter.codec.ProtocolCodecFilter - Processing a MESSAGE_RECEIVED for session 51

Queue : [MESSAGE_RECEIVED, ]
2019.12.15 18:01:37 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event MESSAGE_RECEIVED to session 51
2019.12.15 18:01:37 org.apache.mina.filter.ssl.SslFilter - Session Server[51](SSL): Processing the SSL Data
2019.12.15 18:01:37 org.apache.mina.filter.ssl.SslHandler - Session Server[51](SSL) Processing the received message
2019.12.15 18:01:37 org.apache.mina.filter.ssl.SslFilter - Session Server[51](SSL): Message received : HeapBuffer[pos=0 lim=165 cap=512: FE D6 38 DF 71 8B C5 DA C1 73 C0 54 16 A0 BF 57...]
2019.12.15 18:01:37 org.apache.mina.filter.ssl.SslFilter - Session Server[51](SSL): Processing the SSL Data
2019.12.15 18:01:37 org.apache.mina.filter.ssl.SslHandler - Session Server[51](SSL) Processing the received message
2019.12.15 18:01:37 org.apache.mina.filter.ssl.SslFilter - Session Server[51](SSL): Message received : HeapBuffer[pos=0 lim=256 cap=256: 17 03 03 01 A0 BE DA 98 10 CC 39 E2 99 BE 18 5F...]
2019.12.15 18:01:36 org.jivesoftware.openfire.user.DefaultUserProvider - getUsers results: admin,antonio,bruno,carlos,demo,focus,frank,ivanilson,jenkins,kalyandra,kleber,leandro,maycon,michel,rodrigo,romilso,testea1,thayana,thayron,thiego,.
2019.12.15 18:01:36 org.jivesoftware.openfire.user.DefaultUserProvider - Results: 20

Queue : [MESSAGE_SENT, ]
2019.12.15 18:01:33 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event MESSAGE_SENT to session 51
2019.12.15 18:01:33 org.apache.mina.filter.ssl.SslFilter - Session Server[51](SSL): Writing Message : WriteRequest: HeapBuffer[pos=0 lim=36 cap=64: 3C 61 20 78 6D 6C 6E 73 3D 27 75 72 6E 3A 78 6D...]

Queue : [MESSAGE_SENT, ]
2019.12.15 18:01:33 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event MESSAGE_SENT to session 51
2019.12.15 18:01:33 org.apache.mina.filter.ssl.SslFilter - Session Server[51](SSL): Writing Message : WriteRequest: HeapBuffer[pos=0 lim=77 cap=4096: 3C 69 71 20 74 79 70 65 3D 22 72 65 73 75 6C 74...]
2019.12.15 18:01:33 org.apache.mina.filter.codec.ProtocolCodecFilter - Processing a MESSAGE_RECEIVED for session 51

**Comment by Redor** [comment]
I will close that issue (because it is an REST API Server issue)
FYI: We published a new release https://github.com/igniterealtime/openfire-restAPI-plugin/releases which might fixed your issue
