### ISSUE TITLE
adding rest api through gradle

### ISSUE THREAD

**Issue by gamedev93** [igniterealtime/REST-API-Client#9]
Once I sync the gradle project it is ok but when I am starting to run the android app I got an error
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: javax/inject/Inject.class

This error means that there is two dependency with the same name and classes and it is javax.inject 
version 1 and version 2.4.0-b31. 

I hope you can fix it so I can use it our project. Thank you.

**Comment by Redor** [comment]
Are you using the latest version? (1.1.2)? 
I could not find the problem in the current version.

**Comment by gamedev93** [comment]
Yes, the latest one, but I fixed the problem if I will exclude the version 1 dependency and just use the 2.4.0-b31. 

compile ('org.igniterealtime:rest-api-client:1.1.2'){
        exclude group: 'javax.inject', module: 'javax.inject'
    }

This is what I did to exclude the javax.inject:javax.inject:1
